spring:
  data:
    mongodb:
      authentication-database: admin
      database: tech-ecommerce
      port: 27017
      host: mongodb.cedesistemas.local

app:
  loyalty:
    points-conversion-rate: 1000
